[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
option_contract = "FJHiFT7Deh8mKNzQDjBveWpirgTCdNDfnLTnWec1LxdT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
