[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
option_contract = "6PJkfHcuDPttDRBPUPwc7NryNW8vk3uL9ffbmUMGqqs1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=9eacaf82-7f99-42de-a536-d553d79c2ba5"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
