[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
option_contract = "8vBhep6xtD3WfgJUzZdsBwrDD1dUSnhPDAjp7f4THWNE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
